### ISSUE TITLE
Z height of buttons is tall compared to Sanwa or Seimitsu buttons

### ISSUE THREAD

**Issue by jsoltren** [TheTrainGoes/GP2040-Projects#2]
I’d love to have a variant of these assemblies where the MX switches themselves sit lower, even if it means the lower housing is taller. With Sanwa and Seimitsu buttons, the button tops sit flush in Z with the lower assembly when fully depressed. I feel like the buttons on yours just stick up way too high, I’d love it if they sat about 1.5 to 2mm lower. I’m using Cherry MX Speed Silver switches.

From left to right: Seimitsu, OSBMX, Sanwa

![IMG_7264](https://user-images.githubusercontent.com/1208477/221446017-09285f74-4233-4b9e-89aa-b9a8a6b2f2a6.jpg)

![IMG_7265](https://user-images.githubusercontent.com/1208477/221446023-403314a8-0990-4eff-a7e2-cf1e155135f0.jpg)

**Comment by TheTrainGoes** [comment]
There are a few things going on that are contributing to this.

1 - These are floating plungers unlike the Sanwa or Seimitsu buttons.  Each of the other buttons has a vertical limiting catch and buttons with shorter total movement / actuation.  

2 - The overall rim of these buttons is smaller than the Sanwa and Seimitsu which is giving it the illusion of having a plunger that sits higher up

3 - Cherry Speed Silvers sit a bit higher than the Outemu switches do which also compounds the issue in 1.

I would like to see how these sit and feel with the Outemu switches overall.  

Past that we would need to drop down the hosing by around 1mm, increase the rim hight by another mm and have the plunger contact the housing before fully actuating the switch.  This may not be ideal as it will also limit users to using switches with a low actuation point.  

Will consider this one a maybe since these were primarily modified to be used with Outemu Silent Peach switches.

**Comment by TheTrainGoes** [comment]
Closing this as not planned.
